modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="yotatech"
version="0.1.1"
displayName="Yota-Tech"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Fortranguy, grenfoll"

[[dependencies.yotatech]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




